### PR TITLE
updated footer

### PR DESCRIPTION
**Pull request by bineetNaidu**
-- add fontawesome for icons
-- add footer styles
-- copied gamergram.ico to src for footer img

### CODE REVIEW

**Comment by MeghalBisht** [comment]
@bineetNaidu  Please add screenshot for the same! Then I will merge it

**Comment by bineetNaidu** [comment]
> @bineetNaidu Please add screenshot for the same! Then I will merge it

how i will i add the screenshot i mean it has to on the projects folder right??

**Comment by MeghalBisht** [comment]
@bineetNaidu  Run the app on your local, take a screenshot of the footer and while adding a comment here, there is an option to "attach files by dragging and dropping". 
2020-10-13 (4)_LI

**Comment by bineetNaidu** [comment]
Screenshot from 2020-10-13 11-57-28
 here is the screen shot of the PR

**Comment by MeghalBisht** [comment]
@bineetNaidu  Looks awesome! Thanks, will add you to the contributors list once I make it. Thanks a lot 👍

**Comment by bineetNaidu** [comment]
Thanks a lot. In future is you need any help you can always ask.

**Comment by MeghalBisht** [comment]
@bineetNaidu  Yes I am opening one issue for Contributors page where names and images of all contributors would be displayed.
If you want I can assign you :)

**Pull request merged**
